---
title: "byrace"
author: "Ziqi Zhou"
date: "7/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE,message=FALSE,warning=FALSE}
byage0518 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0518.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-18",
         day = as.Date(day))

byage0519 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0519.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-19",
         day = as.Date(day))
byage0520 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0520.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-20",
         day = as.Date(day))
byage0521 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0521.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-21",
         day = as.Date(day))
byage0522 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0522.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-22",
         day = as.Date(day))
byage0523 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0523.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-23",
         day = as.Date(day))
byage0524 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0524.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-24",
         day = as.Date(day))
byage0525 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0525.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-25",
         day = as.Date(day))
byage0526 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0526.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-26",
         day = as.Date(day))
byage0527 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0527.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-27",
         day = as.Date(day))
byage0528 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0528.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-28",
         day = as.Date(day))
byage0529 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0529.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-29",
         day = as.Date(day))
byage0530 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0530.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-30",
         day = as.Date(day))
byage0531 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0531.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-31",
         day = as.Date(day))

byage0601 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0601.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-01",
         day = as.Date(day))
byage0602 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0602.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-02",
         day = as.Date(day))
byage0603 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0603.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-03",
         day = as.Date(day))
byage0604 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0604.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-04",
         day = as.Date(day))
byage0605 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0605.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count") %>% 
  mutate(day = "2020-06-05",
         day = as.Date(day))

byage0606 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0606.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-06",
         day = as.Date(day))
byage0607 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0607.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-07",
         day = as.Date(day))
byage0608 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0608.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-08",
         day = as.Date(day))
byage0609 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0609.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-09",
         day = as.Date(day))

byage0610 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0610.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-10",
         day = as.Date(day))
byage0611 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0611.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-11",
         day = as.Date(day))
byage0612 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0612.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-12",
         day = as.Date(day))
byage0613 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0613.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-13",
         day = as.Date(day))
byage0614 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0614.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-14",
         day = as.Date(day))

byage0615 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0615.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-15",
         day = as.Date(day))
byage0616 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0616.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-16",
         day = as.Date(day))
byage0617 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0617.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-17",
         day = as.Date(day))


byage0618 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0618.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-18",
         day = as.Date(day))
byage0619 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0619.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-19",
         day = as.Date(day))
byage0620 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0620.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-20",
         day = as.Date(day))


byage0621 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0621.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-21",
         day = as.Date(day))
byage0622 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0622.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-22",
         day = as.Date(day))
byage0623 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0623.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-23",
         day = as.Date(day))

byage0624 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0624.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-24",
         day = as.Date(day))
byage0625 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0625.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-25",
         day = as.Date(day))
byage0626 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0626.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-26",
         day = as.Date(day))

byage0627 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0627.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-27",
         day = as.Date(day))

byage0628 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0628.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-28",
         day = as.Date(day))

byage0630 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0630.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-30",
         day = as.Date(day))

byage0701 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0701.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-01",
         day = as.Date(day))

byage0702 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0702.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-02",
         day = as.Date(day))

byage0703 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0703.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-03",
         day = as.Date(day))

byage0704 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0704.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-04",
         day = as.Date(day))

byage0705 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))

byage0705 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))
byage0706 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0706.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-06",
         day = as.Date(day))

byage0707 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0707.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-07",
         day = as.Date(day))

byage0708 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0708.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-08",
         day = as.Date(day))
byage0709 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0709.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-09",
         day = as.Date(day))

byage0710 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0710.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-10",
         day = as.Date(day))

byage0711 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0711.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-11",
         day = as.Date(day))
byage0712 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0712.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-12",
         day = as.Date(day))

byage0713 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0713.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-13",
         day = as.Date(day))

byage0714 = read_csv("./data/data_covid_demo/boros_by_race/boroughs-by-race0714.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE_ADJ,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-14",
         day = as.Date(day))
```

```{r,include=FALSE,message=FALSE,warning=FALSE}
byage = rbind(byage0518,byage0519)
byage = rbind(byage,byage0520)
byage = rbind(byage,byage0521)
byage = rbind(byage,byage0522)
byage = rbind(byage,byage0523)
byage = rbind(byage,byage0524)
byage = rbind(byage,byage0525)
byage = rbind(byage,byage0526)
byage = rbind(byage,byage0527)
byage = rbind(byage,byage0528)
byage = rbind(byage,byage0529)
byage = rbind(byage,byage0530)
byage = rbind(byage,byage0531)
byage = rbind(byage,byage0601)
byage = rbind(byage,byage0602)
byage = rbind(byage,byage0603)
byage = rbind(byage,byage0604)
byage = rbind(byage,byage0605)
byage = rbind(byage,byage0606)
byage = rbind(byage,byage0607)
byage = rbind(byage,byage0608)
byage = rbind(byage,byage0609)
byage = rbind(byage,byage0610)
byage = rbind(byage,byage0611)
byage = rbind(byage,byage0612)
byage = rbind(byage,byage0613)
byage = rbind(byage,byage0614)
byage = rbind(byage,byage0615)
byage = rbind(byage,byage0616)
byage = rbind(byage,byage0617)
byage = rbind(byage,byage0618)
byage = rbind(byage,byage0619)
byage = rbind(byage,byage0620)
byage = rbind(byage,byage0621)
byage = rbind(byage,byage0622)
byage = rbind(byage,byage0623)
byage = rbind(byage,byage0624)
byage = rbind(byage,byage0625)
byage = rbind(byage,byage0626)
byage = rbind(byage,byage0627)
byage = rbind(byage,byage0628)

byage = rbind(byage,byage0630)
byage = rbind(byage,byage0701)
byage = rbind(byage,byage0702)
byage = rbind(byage,byage0703)
byage = rbind(byage,byage0704)
byage = rbind(byage,byage0705)
byage = rbind(byage,byage0706)
byage = rbind(byage,byage0707)
byage = rbind(byage,byage0708)
byage = rbind(byage,byage0709)
byage = rbind(byage,byage0710)
byage = rbind(byage,byage0711)
byage = rbind(byage,byage0712)
byage = rbind(byage,byage0713)
byage = rbind(byage,byage0714)

BYRACE = byage
```


```{r,include=FALSE,message=FALSE,warning=FALSE}
write_csv(BYRACE,"./distribution_of_covid-19/data/BYRACE_demoage_data.csv")
```


```{r,include=FALSE,message=FALSE,warning=FALSE}
boro_age_case_count = byage %>% 
  filter(str_detect(location_n_event,"CASE_COUNT"))

boro_age_hosp_count = byage %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_COUNT"))

boro_age_death_count = byage %>% 
  filter(str_detect(location_n_event,"DEATH_COUNT"))

boro_age_case_rate = byage %>% 
  filter(str_detect(location_n_event,"CASE_RATE"))

boro_age_hosp_rate = byage %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_RATE"))

boro_age_death_rate = byage %>% 
  filter(str_detect(location_n_event,"DEATH_RATE"))

```