---
title: "bysex"
author: "Ziqi Zhou"
date: "7/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rgdal)
library(sp)
library(tmap)  
library(readxl)
library(viridis)
library(leaflet)
library(tigris)
library(plotly)
library(ggthemes)
library(RColorBrewer)
library(patchwork)
```

```{r}
bysex0518 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0518.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-18",
         day = as.Date(day))

bysex0519 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0519.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-19",
         day = as.Date(day))
bysex0520 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0520.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-20",
         day = as.Date(day))
bysex0521 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0521.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-21",
         day = as.Date(day))
bysex0522 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0522.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-22",
         day = as.Date(day))
bysex0523 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0523.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-23",
         day = as.Date(day))
bysex0524 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0524.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-24",
         day = as.Date(day))
bysex0525 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0525.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-25",
         day = as.Date(day))
bysex0526 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0526.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-26",
         day = as.Date(day))
bysex0527 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0527.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-27",
         day = as.Date(day))
bysex0528 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0528.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-28",
         day = as.Date(day))
bysex0529 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0529.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-29",
         day = as.Date(day))
bysex0530 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0530.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-30",
         day = as.Date(day))
bysex0531 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0531.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-31",
         day = as.Date(day))

bysex0601 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0601.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-01",
         day = as.Date(day))
bysex0602 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0602.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-02",
         day = as.Date(day))
bysex0603 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0603.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-03",
         day = as.Date(day))
bysex0604 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0604.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-04",
         day = as.Date(day))
bysex0605 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0605.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count") %>% 
  mutate(day = "2020-06-05",
         day = as.Date(day))

bysex0606 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0606.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-06",
         day = as.Date(day))
bysex0607 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0607.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-07",
         day = as.Date(day))
bysex0608 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0608.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-08",
         day = as.Date(day))
bysex0609 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0609.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-09",
         day = as.Date(day))

bysex0610 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0610.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-10",
         day = as.Date(day))
bysex0611 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0611.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-11",
         day = as.Date(day))
bysex0612 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0612.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-12",
         day = as.Date(day))
bysex0613 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0613.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-13",
         day = as.Date(day))
bysex0614 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0614.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-14",
         day = as.Date(day))

bysex0615 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0615.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-15",
         day = as.Date(day))
bysex0616 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0616.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-16",
         day = as.Date(day))
bysex0617 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0617.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-17",
         day = as.Date(day))


bysex0618 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0618.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-18",
         day = as.Date(day))
bysex0619 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0619.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-19",
         day = as.Date(day))
bysex0620 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0620.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-20",
         day = as.Date(day))


bysex0621 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0621.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-21",
         day = as.Date(day))
bysex0622 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0622.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-22",
         day = as.Date(day))
bysex0623 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0623.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-23",
         day = as.Date(day))

bysex0624 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0624.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-24",
         day = as.Date(day))
bysex0625 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0625.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-25",
         day = as.Date(day))
bysex0626 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0626.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-26",
         day = as.Date(day))

bysex0627 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0627.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-27",
         day = as.Date(day))

bysex0628 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0628.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-28",
         day = as.Date(day))

bysex0630 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0630.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-30",
         day = as.Date(day))

bysex0701 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0701.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-01",
         day = as.Date(day))

bysex0702 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0702.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-02",
         day = as.Date(day))

bysex0703 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0703.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-03",
         day = as.Date(day))

bysex0704 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0704.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-04",
         day = as.Date(day))

bysex0705 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))

bysex0705 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))
bysex0706 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0706.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-06",
         day = as.Date(day))

bysex0707 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0707.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-07",
         day = as.Date(day))

bysex0708 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0708.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-08",
         day = as.Date(day))
bysex0709 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0709.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-09",
         day = as.Date(day))

bysex0710 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0710.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-10",
         day = as.Date(day))

bysex0711 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0711.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-11",
         day = as.Date(day))
bysex0712 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0712.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-12",
         day = as.Date(day))

bysex0713 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0713.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-13",
         day = as.Date(day))

bysex0714 = read_csv("./data/data_covid_demo/boros_by_sex/boroughs-by-sex0714.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-14",
         day = as.Date(day))
```

```{r,include=FALSE,message=FALSE,warning=FALSE}
bysex= rbind(bysex0518,bysex0519)
bysex = rbind(bysex,bysex0520)
bysex = rbind(bysex,bysex0521)
bysex = rbind(bysex,bysex0522)
bysex = rbind(bysex,bysex0523)
bysex = rbind(bysex,bysex0524)
bysex = rbind(bysex,bysex0525)
bysex = rbind(bysex,bysex0526)
bysex = rbind(bysex,bysex0527)
bysex = rbind(bysex,bysex0528)
bysex = rbind(bysex,bysex0529)
bysex = rbind(bysex,bysex0530)
bysex = rbind(bysex,bysex0531)
bysex = rbind(bysex,bysex0601)
bysex = rbind(bysex,bysex0602)
bysex = rbind(bysex,bysex0603)
bysex = rbind(bysex,bysex0604)
bysex = rbind(bysex,bysex0605)
bysex = rbind(bysex,bysex0606)
bysex = rbind(bysex,bysex0607)
bysex = rbind(bysex,bysex0608)
bysex = rbind(bysex,bysex0609)
bysex = rbind(bysex,bysex0610)
bysex = rbind(bysex,bysex0611)
bysex = rbind(bysex,bysex0612)
bysex = rbind(bysex,bysex0613)
bysex = rbind(bysex,bysex0614)
bysex = rbind(bysex,bysex0615)
bysex = rbind(bysex,bysex0616)
bysex = rbind(bysex,bysex0617)
bysex = rbind(bysex,bysex0618)
bysex = rbind(bysex,bysex0619)
bysex = rbind(bysex,bysex0620)
bysex = rbind(bysex,bysex0621)
bysex = rbind(bysex,bysex0622)
bysex = rbind(bysex,bysex0623)
bysex = rbind(bysex,bysex0624)
bysex = rbind(bysex,bysex0625)
bysex = rbind(bysex,bysex0626)
bysex = rbind(bysex,bysex0627)
bysex = rbind(bysex,bysex0628)

bysex = rbind(bysex,bysex0630)
bysex = rbind(bysex,bysex0701)
bysex = rbind(bysex,bysex0702)
bysex = rbind(bysex,bysex0703)
bysex = rbind(bysex,bysex0704)
bysex = rbind(bysex,bysex0705)
bysex = rbind(bysex,bysex0706)
bysex = rbind(bysex,bysex0707)
bysex = rbind(bysex,bysex0708)
bysex = rbind(bysex,bysex0709)
bysex = rbind(bysex,bysex0710)
bysex = rbind(bysex,bysex0711)
bysex = rbind(bysex,bysex0712)
bysex = rbind(bysex,bysex0713)
bysex = rbind(bysex,bysex0714)

write_csv(bysex,"./distribution_of_covid-19/data/demoage_data_sex.csv")
```


```{r,include=FALSE,message=FALSE,warning=FALSE}
boro_sex_case_count = bysex %>% 
  filter(str_detect(location_n_event,"CASE_COUNT"))

boro_sex_hosp_count = bysex %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_COUNT"))

boro_sex_death_count = bysex %>% 
  filter(str_detect(location_n_event,"DEATH_COUNT"))

boro_sex_case_rate = bysex %>% 
  filter(str_detect(location_n_event,"CASE_RATE"))

boro_sex_hosp_rate = bysex %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_RATE"))

boro_sex_death_rate = bysex %>% 
  filter(str_detect(location_n_event,"DEATH_RATE"))

```

