---
title: "comordity bug"
author: "Ziqi Zhou"
date: "7/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# data source
asthma at NTA level
http://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2387,4466a0,11,Summarize

or
```{r}
asthma = read.csv("./data/Asthma Emergency Department Visits (Adults) by NTA.csv",skip = 12) %>% 
  janitor::clean_names() %>% 
  filter(x2012_2014 == "2012-2014") %>% 
  rename(geotypename = borough,
         year = x2012_2014,
         borough = staten_island,
         NTAName = staten_island_1,
         id = x5,
         average_annual_age_adjusted_rate = x77_7,
         average_annual_number = x2_773,
         average_annual_rate = x75_3) %>% 
  select(-x,-x_1,-x_2,-x_3,-asthma_emergency_department_visits_adults_by_nta) %>% 
  mutate(NTAName = as.character(NTAName))
```


map nta data source


```{r}
library(sp)
library(rgdal)
my_spdf <- readOGR( 
  dsn= paste0("./data/nynta_20b") , 
  layer="TM_WORLD_BORDERS_SIMPL-0.3",
  verbose=FALSE
)

spdf = rgdal::readOGR("./Geography-resources/MODZCTA_2010_WGS1984.geo.json")


shp <- readOGR(dsn = "./data/nynta_20b/nynta.shp", stringsAsFactors = F)
shpnta = shp@data$NTAName
shpnta = as.data.frame(shpnta)
write_excel_csv(shpnta, "./data/shpnta.csv")

ast_nta = as.data.frame(ast_nta)
write_excel_csv(ast_nta, "./data/astnta.csv")

#however this step did not work.
data_as = geo_join(shp,asthma,"NTAName","NTAName")


#then we could use the data and the ggplot function to draw the map



```

we want to use geo_join to add the asthma data into the map data so that we could draw a map. However, I could not succeed.

Or we could use other method to draw this map.
