---
title: Comorbidity
output: html_document
---

# comorbidity

## diseases


```{r include=FALSE}
library(rgdal)
library(sp)
library(tidyverse)

library(tmap)  

library(readxl)
library(viridis)
library(leaflet)
library(tigris)
library(plotly)


```

```{r}
counties<-readOGR("./data/nynta_20b/nynta.shp", layer="nynta")

ggplot() +  geom_polygon(data=counties, aes(x=long, y=lat, group=group))

proj4string(counties)
```


```{r}
spdf = rgdal::readOGR("Geography-resources/MODZCTA_2010_WGS1984.geo.json")

spdf@data

asthma = read.csv("/Users/ziqizhou/Desktop/Asthma Emergency Department Visits (Adults).csv") %>% 
  mutate(MODIFIED_ZCTA = as.character(MODIFIED_ZCTA))

data_map = geo_join(spdf,asthma,"MODZCTA","MODIFIED_ZCTA")
data_map@data

pal <- colorNumeric("Reds", domain=asthma$Estimated.Annual.Rate..per.10.000.residents.)
  
  popup_sb <- paste0("Neighborhood Name: ", as.character(asthma$Geography),
                     "<br>", 
                     "MODZCTA: ", as.character(asthma$MODIFIED_ZCTA),
                     "<br>", 
                     "Number: ", as.character(asthma$Estimated.Annual.Rate..per.10.000.residents.)
  )
  
  p1 = leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    setView(lng = -73.99653, lat = 40.75074, zoom = 10) %>% 
    addPolygons(data =  data_map , 
                fillColor = ~pal(asthma$Estimated.Annual.Rate..per.10.000.residents.), 
                fillOpacity = 0.7, 
                weight = 0.2, 
                smoothFactor = 0.2, 
                popup = ~popup_sb) %>%
    addLegend(pal = pal, 
              values =  asthma$Estimated.Annual.Rate..per.10.000.residents., 
              position = "bottomright", 
              title = "Number")
  p1
```



