---
title: "covid_by_demographics"
author: "Ziqi Zhou"
date: "7/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rgdal)
library(sp)
library(tmap)  
library(readxl)
library(viridis)
library(leaflet)
library(tigris)
library(plotly)

boromap = rgdal::readOGR("./Geography-resources/Borough Boundaries.geojson")
boromap@data
```

# by age
```{r}
#read the data

byage0518 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0518.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-18",
         day = as.Date(day))

byage0519 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0519.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-19",
         day = as.Date(day))
byage0520 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0520.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-20",
         day = as.Date(day))
byage0521 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0521.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-21",
         day = as.Date(day))
byage0522 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0522.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-22",
         day = as.Date(day))
byage0523 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0523.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-23",
         day = as.Date(day))
byage0524 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0524.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-24",
         day = as.Date(day))
byage0525 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0525.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-25",
         day = as.Date(day))
byage0526 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0526.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-26",
         day = as.Date(day))
byage0527 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0527.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-27",
         day = as.Date(day))
byage0528 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0528.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-28",
         day = as.Date(day))
byage0529 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0529.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-29",
         day = as.Date(day))
byage0530 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0530.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-30",
         day = as.Date(day))
byage0531 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0531.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-31",
         day = as.Date(day))

byage0601 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0601.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-01",
         day = as.Date(day))
byage0602 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0602.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-02",
         day = as.Date(day))
byage0603 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0603.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-03",
         day = as.Date(day))
byage0604 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0604.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-04",
         day = as.Date(day))
byage0605 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0605.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count") %>% 
  mutate(day = "2020-06-05",
         day = as.Date(day))

byage0606 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0606.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-06",
         day = as.Date(day))
byage0607 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0607.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-07",
         day = as.Date(day))
byage0608 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0608.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-08",
         day = as.Date(day))
byage0609 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0609.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-09",
         day = as.Date(day))

byage0610 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0610.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-10",
         day = as.Date(day))
byage0611 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0611.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-11",
         day = as.Date(day))
byage0612 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0612.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-12",
         day = as.Date(day))
byage0613 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0613.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-13",
         day = as.Date(day))
byage0614 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0614.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-14",
         day = as.Date(day))

byage0615 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0615.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-15",
         day = as.Date(day))
byage0616 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0616.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-16",
         day = as.Date(day))
byage0617 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0617.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-17",
         day = as.Date(day))


byage0618 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0618.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-18",
         day = as.Date(day))
byage0619 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0619.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-19",
         day = as.Date(day))
byage0620 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0620.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-20",
         day = as.Date(day))


byage0621 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0621.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-21",
         day = as.Date(day))
byage0622 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0622.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-22",
         day = as.Date(day))
byage0623 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0623.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-23",
         day = as.Date(day))

byage0624 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0624.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-24",
         day = as.Date(day))
byage0625 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0625.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-25",
         day = as.Date(day))
byage0626 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0626.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-26",
         day = as.Date(day))

byage0627 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0627.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-27",
         day = as.Date(day))

byage0628 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0628.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-28",
         day = as.Date(day))

byage0630 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0630.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-30",
         day = as.Date(day))
```

```{r}
byage = rbind(byage0518,byage0519)
byage = rbind(byage,byage0520)
byage = rbind(byage,byage0521)
byage = rbind(byage,byage0522)
byage = rbind(byage,byage0523)
byage = rbind(byage,byage0524)
byage = rbind(byage,byage0525)
byage = rbind(byage,byage0526)
byage = rbind(byage,byage0527)
byage = rbind(byage,byage0528)
byage = rbind(byage,byage0529)
byage = rbind(byage,byage0530)
byage = rbind(byage,byage0531)
byage = rbind(byage,byage0601)
byage = rbind(byage,byage0602)
byage = rbind(byage,byage0603)
byage = rbind(byage,byage0604)
byage = rbind(byage,byage0605)
byage = rbind(byage,byage0606)
byage = rbind(byage,byage0607)
byage = rbind(byage,byage0608)
byage = rbind(byage,byage0609)
byage = rbind(byage,byage0610)
byage = rbind(byage,byage0611)
byage = rbind(byage,byage0612)
byage = rbind(byage,byage0613)
byage = rbind(byage,byage0614)
byage = rbind(byage,byage0615)
byage = rbind(byage,byage0616)
byage = rbind(byage,byage0617)
byage = rbind(byage,byage0618)
byage = rbind(byage,byage0619)
byage = rbind(byage,byage0620)
byage = rbind(byage,byage0621)
byage = rbind(byage,byage0622)
byage = rbind(byage,byage0623)
byage = rbind(byage,byage0624)
byage = rbind(byage,byage0625)
byage = rbind(byage,byage0626)
byage = rbind(byage,byage0627)
byage = rbind(byage,byage0628)

byage = rbind(byage,byage0630)
```


```{r}
boro_age_case_count = byage %>% 
  filter(str_detect(location_n_event,"CASE_COUNT"))


boro_age_hosp_count = byage %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_COUNT"))

boro_age_death_count = byage %>% 
  filter(str_detect(location_n_event,"DEATH_COUNT"))

boro_age_case_rate = byage %>% 
  filter(str_detect(location_n_event,"CASE_RATE"))

boro_age_hosp_rate = byage %>% 
  filter(str_detect(location_n_event,"HOSPITALIZED_RATE"))

boro_age_death_rate = byage %>% 
  filter(str_detect(location_n_event,"DEATH_RATE"))

```

258x5

```{r}
boros = rep(c("Brooklyn","Bronx","Manhattan","Queens","Staten Island"),258)

boro_age_case_count = boro_age_case_count %>% 
  mutate(location = boros)

data1 = geo_join(boromap,boro_age_case_count,"boro_name","location")
data1@data
```


```{r}

    
    boro_age_case_count = subset(boro_age_case_count, !is.na(count))
    pal <- colorNumeric("Greens", domain=boro_age_case_count$count)
    
    popup_sb <- paste0("Neighborhood Name: ", as.character(boro_age_case_count$neighborhood_name),
                       "<br>", 
                       "MODZCTA: ", as.character(boro_age_case_count$zipcode),
                       "<br>", 
                       "Total Number of Cumulative Positive Cases: ", as.character(boro_age_case_count$count)
    )
    
    p1 = leaflet() %>%
        addProviderTiles("CartoDB.Positron") %>%
        setView(lng = -73.99653, lat = 40.75074, zoom = 10) %>% 
        addPolygons(data =  data1 , 
                    fillColor = ~pal(boro_age_case_count$count), 
                    fillOpacity = 0.7, 
                    weight = 0.2, 
                    smoothFactor = 0.2, 
                    popup = ~popup_sb) %>%
        addLegend(pal = pal, 
                  values =  boro_age_case_count$count, 
                  position = "bottomright", 
                  title = "Number")
    p1
```

