---
title: "covid_by_demographics"

output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rgdal)
library(sp)
library(tmap)  
library(readxl)
library(viridis)
library(leaflet)
library(tigris)
library(plotly)
library(ggthemes)
library(RColorBrewer)
library(patchwork)

```

# by age
```{r, include=FALSE,message=FALSE,warning=FALSE}
#read the data

byage0518 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0518.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-18",
         day = as.Date(day))

byage0519 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0519.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-19",
         day = as.Date(day))
byage0520 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0520.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-20",
         day = as.Date(day))
byage0521 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0521.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-21",
         day = as.Date(day))
byage0522 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0522.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-22",
         day = as.Date(day))
byage0523 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0523.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-23",
         day = as.Date(day))
byage0524 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0524.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-24",
         day = as.Date(day))
byage0525 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0525.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-25",
         day = as.Date(day))
byage0526 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0526.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-26",
         day = as.Date(day))
byage0527 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0527.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-27",
         day = as.Date(day))
byage0528 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0528.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-28",
         day = as.Date(day))
byage0529 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0529.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-29",
         day = as.Date(day))
byage0530 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0530.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-30",
         day = as.Date(day))
byage0531 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0531.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-05-31",
         day = as.Date(day))

byage0601 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0601.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-01",
         day = as.Date(day))
byage0602 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0602.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-02",
         day = as.Date(day))
byage0603 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0603.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-03",
         day = as.Date(day))
byage0604 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0604.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-04",
         day = as.Date(day))
byage0605 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0605.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count") %>% 
  mutate(day = "2020-06-05",
         day = as.Date(day))

byage0606 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0606.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-06",
         day = as.Date(day))
byage0607 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0607.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-07",
         day = as.Date(day))
byage0608 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0608.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-08",
         day = as.Date(day))
byage0609 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0609.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-09",
         day = as.Date(day))

byage0610 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0610.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-10",
         day = as.Date(day))
byage0611 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0611.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-11",
         day = as.Date(day))
byage0612 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0612.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-12",
         day = as.Date(day))
byage0613 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0613.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-13",
         day = as.Date(day))
byage0614 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0614.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-14",
         day = as.Date(day))

byage0615 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0615.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-15",
         day = as.Date(day))
byage0616 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0616.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-16",
         day = as.Date(day))
byage0617 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0617.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-17",
         day = as.Date(day))


byage0618 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0618.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-18",
         day = as.Date(day))
byage0619 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0619.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-19",
         day = as.Date(day))
byage0620 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0620.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-20",
         day = as.Date(day))


byage0621 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0621.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-21",
         day = as.Date(day))
byage0622 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0622.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-22",
         day = as.Date(day))
byage0623 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0623.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-23",
         day = as.Date(day))

byage0624 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0624.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-24",
         day = as.Date(day))
byage0625 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0625.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-25",
         day = as.Date(day))
byage0626 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0626.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-26",
         day = as.Date(day))

byage0627 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0627.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-27",
         day = as.Date(day))

byage0628 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0628.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-28",
         day = as.Date(day))

byage0630 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0630.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-06-30",
         day = as.Date(day))

byage0701 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0701.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-01",
         day = as.Date(day))

byage0702 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0702.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-02",
         day = as.Date(day))

byage0703 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0703.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-03",
         day = as.Date(day))

byage0704 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0704.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-04",
         day = as.Date(day))

byage0705 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))

byage0705 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0705.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-05",
         day = as.Date(day))
byage0706 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0706.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-06",
         day = as.Date(day))

byage0707 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0707.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-07",
         day = as.Date(day))

byage0708 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0708.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-08",
         day = as.Date(day))
byage0709 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0709.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-09",
         day = as.Date(day))

byage0710 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0710.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-10",
         day = as.Date(day))

byage0711 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0711.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-11",
         day = as.Date(day))
byage0712 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0712.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-12",
         day = as.Date(day))

byage0713 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0713.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-13",
         day = as.Date(day))

byage0714 = read_csv("./data/data_covid_demo/boros_by_age/boroughs-by-age0714.csv") %>% 
  pivot_longer(BK_CASE_COUNT:SI_DEATH_RATE,
               names_to = "location_n_event",
               values_to = "count")%>% 
  mutate(day = "2020-07-14",
         day = as.Date(day))
```

```{r,include=FALSE,message=FALSE,warning=FALSE}
byage = rbind(byage0518,byage0519)
byage = rbind(byage,byage0520)
byage = rbind(byage,byage0521)
byage = rbind(byage,byage0522)
byage = rbind(byage,byage0523)
byage = rbind(byage,byage0524)
byage = rbind(byage,byage0525)
byage = rbind(byage,byage0526)
byage = rbind(byage,byage0527)
byage = rbind(byage,byage0528)
byage = rbind(byage,byage0529)
byage = rbind(byage,byage0530)
byage = rbind(byage,byage0531)
byage = rbind(byage,byage0601)
byage = rbind(byage,byage0602)
byage = rbind(byage,byage0603)
byage = rbind(byage,byage0604)
byage = rbind(byage,byage0605)
byage = rbind(byage,byage0606)
byage = rbind(byage,byage0607)
byage = rbind(byage,byage0608)
byage = rbind(byage,byage0609)
byage = rbind(byage,byage0610)
byage = rbind(byage,byage0611)
byage = rbind(byage,byage0612)
byage = rbind(byage,byage0613)
byage = rbind(byage,byage0614)
byage = rbind(byage,byage0615)
byage = rbind(byage,byage0616)
byage = rbind(byage,byage0617)
byage = rbind(byage,byage0618)
byage = rbind(byage,byage0619)
byage = rbind(byage,byage0620)
byage = rbind(byage,byage0621)
byage = rbind(byage,byage0622)
byage = rbind(byage,byage0623)
byage = rbind(byage,byage0624)
byage = rbind(byage,byage0625)
byage = rbind(byage,byage0626)
byage = rbind(byage,byage0627)
byage = rbind(byage,byage0628)

byage = rbind(byage,byage0630)
byage = rbind(byage,byage0701)
byage = rbind(byage,byage0702)
byage = rbind(byage,byage0703)
byage = rbind(byage,byage0704)
byage = rbind(byage,byage0705)
byage = rbind(byage,byage0706)
byage = rbind(byage,byage0707)
byage = rbind(byage,byage0708)
byage = rbind(byage,byage0709)
byage = rbind(byage,byage0710)
byage = rbind(byage,byage0711)
byage = rbind(byage,byage0712)
byage = rbind(byage,byage0713)
byage = rbind(byage,byage0714)
```


```{r,include=FALSE,message=FALSE,warning=FALSE}
byage = byage %>% separate(location_n_event,
                   into = c("location","outcome"),sep = 3) %>% 
  separate(location, into = c("boro", "x"),sep = 2) %>% 
  dplyr:: select(-x)

#write_csv(byage,"./distribution_of_covid-19/data/demoage_data.csv")
```

### Rate per 100,000 people

```{r,include=FALSE,message=FALSE,warning=FALSE}



#boro_age_hosp_count = byage %>% 
#  filter(str_detect(location_n_event,"HOSPITALIZED_COUNT"))


```

```{r, include=FALSE}
#boromap = rgdal::readOGR("./Geography-resources/Borough Boundaries.geojson")
#boromap@data
```

342x5




Bar chart ; pie chart; Time trend
### Bar chart

```{r}
a = byage %>% filter(day == "2020-05-18" & group != "Boroughwide") %>% 
  ggplot(aes(fill = group, y = count, x = boro)) + 
  geom_bar(position="dodge", stat="identity")

ggplotly(a)
```


```{r}
 
a =  byage %>% filter(day == max(byage$day) & group != "Boroughwide") %>% 
   ggplot(aes(fill = group, y = count, x = boro)) + 
  geom_bar(position="stack", stat="identity") + 
   facet_grid(~outcome)

ggplotly(a)

```


```{r}
 b =  bysex %>%  filter(day == max(bysex$day) & group != "Boroughwide") %>% 
      ggplot(aes(fill = group, y = count, x = boro)) + 
      geom_bar(position="stack", stat="identity") + 
      facet_grid(~outcome)
    
    ggplotly(b)
    
    
plotting_df <- bysex %>% 
  filter(day == max(bysex$day) & group != "Boroughwide") %>% 
  mutate(count = if_else(group == "Male", -count, count))

temp_df <- plotting_df %>%
  filter(group == "Female") %>% 
  arrange(count)
the_order <- temp_df$boro
    
 
p <- 
  plotting_df %>%
  ggplot(aes(x = boro, y = count, group = group, fill = group)) +
  geom_bar(stat = "identity", width = 0.75) +
  coord_flip() +
  scale_x_discrete(limits = the_order) +
  # another trick!
  scale_y_continuous(breaks = seq(-35000,35000,5000), 
                     labels = abs(seq(-35000,35000, 5000))) +
  labs(x = "Boroughs", y = "Count", title = "Back-to-back bar chart") +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        panel.background = element_rect(fill =  "grey90")) +
  # reverse the order of items in legend
  # guides(fill = guide_legend(reverse = TRUE)) +
  # change the default colors of bars
  scale_fill_manual(values=c("red", "blue"),
                    name="",
                    breaks=c("Male", "Female"),
                    labels=c("Male", "Female")) 
p
```


```{r}
c =  byrace %>%  filter(day == max(byrace$day) & group != "Boroughwide") %>% 
      ggplot(aes(fill = group, y = count, x = boro)) + 
      geom_bar(position="stack", stat="identity") + 
      facet_grid(~outcome,scales = "free")
    
    ggplotly(c)
    

```


### Time trend
```{r}
c = boro_age_death_rate %>% 
  filter(group == "18-44") %>% 
  ggplot(aes(x = day, y = count ,color = location)) + 
  geom_line()

ggplotly(c)
```
```{r}
c = byage %>% 
  filter(group != "Boroughwide" ) %>% 
  ggplot(aes(x = day, y = count ,color = group, group = group)) + 
  geom_line() + facet_grid(boro~outcome)

ggplotly(c)

Week <- unique(as.Date(cut(byage$day, "week")) + 6)
weeklyage <- byage %>% 
  filter(day %in% Week)

x_min_us = min(weeklyage$day)
x_max_us = max(weeklyage$day)

break.vec <- c(x_min_us, seq(x_min_us, x_max_us, by = "7 days"))

   weeklyage %>% 
      filter(group != "Boroughwide" & outcome == "DEATH_COUNT") %>% 
      
      ggplot(aes(x = day, y = count ,color = group, group = group)) + 
      geom_line(size = 0.3) + geom_point(size = 0.8) + facet_grid(~boro) + 
      theme_minimal() + 
    
     scale_x_date(breaks = break.vec, date_labels = "%m-%d") + 
     theme(axis.text.x = element_text(angle = 45)) 
     

```



```{r, eval = FALSE}
data_to_plot = boro_age_case_count %>% 
  filter(day == "2020-06-30" & 
           location == "Brooklyn" & 
           group != "Boroughwide") 

case_map_data = boro_age_case_count %>% 
  filter(group == "Boroughwide" & day == "2020-06-30") 

case_map = geo_join(boromap,case_map_data,"boro_name" ,"location")

pal <- colorNumeric("Greens", domain=case_map_data $count)
    
    popup_sb <- paste0("BORO Name: ", as.character(case_map_data$location),
                       "<br>", 
                       "Total Number of Cumulative Positive Cases: ", as.character(case_map_data$count)
    )
    
leaflet() %>%
        addProviderTiles("CartoDB.Positron") %>%
        setView(lng = -73.99653, lat = 40.75074, zoom = 10) %>% 
        addPolygons(data =  case_map , 
                    fillColor = ~pal(case_map_data$count), 
                    fillOpacity = 0.7, 
                    weight = 0.2, 
                    smoothFactor = 0.2, 
                    popup = ~popup_sb) %>%
        addLegend(pal = pal, 
                  values =  case_map_data$count, 
                  position = "bottomright", 
                  title = "Number")
```




###  Case Count Age Distribution.

```{r}


data = byage %>% 
  filter(day == "2020-06-30" & 
           
           group != "Boroughwide") 
data = data %>% group_by(boro,outcome) %>% 
  mutate(fraction = count/sum(count))

data$ymax <- cumsum(data$fraction)
data$ymin <- c(0, head(data$ymax, n=-1))


# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$category, "\n value: ", data$count)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=boro)) +
  geom_rect() +
  coord_polar(theta="y") +
  xlim(c(2, 4)) + 
  facet_grid(~outcome)
  
```




```{r}
library(plotly)
```


```{r}

pie1data = byage %>% 
  filter(boro == "BX"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT") %>% mutate(group = factor(group,levels = c("0-17","18-44","45-64","65-74","75+"))) %>% 
  arrange(group)
  
pie2data = byage %>% 
  filter(boro == "BK"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT") %>% mutate(group = factor(group,levels = c("0-17","18-44","45-64","65-74","75+"))) %>% 
  arrange(group)

pie3data = byage %>% 
  filter(boro == "MN"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT") %>% mutate(group = factor(group,levels = c("0-17","18-44","45-64","65-74","75+"))) %>% 
  arrange(group)

pie4data = byage %>% 
  filter(boro == "SI"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT") %>% mutate(group = factor(group,levels = c("0-17","18-44","45-64","65-74","75+"))) %>% 
  arrange(group)

pie5data = byage %>% 
  filter(boro == "QN"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT")%>% mutate(group = factor(group,levels = c("0-17","18-44","45-64","65-74","75+"))) %>% 
  arrange(group)
label1 = paste0("Age Group: ", pie1data$group)
label2 = paste0("Age Group: ", pie2data$group)
label3 = paste0("Age Group: ", pie3data$group)
label4 = paste0("Age Group: ", pie4data$group)
label5 = paste0("Age Group: ", pie5data$group)

fig <- plot_ly(sort = FALSE)

    fig <- fig %>% add_trace(data = pie1data %>% select(group,count), 
                           labels = ~label1, values = ~count,
                           type = 'pie',
                           
                           name =  ~pie1data$boro, domain = list(row = 0, column = 0)
                           )
    fig <- fig %>% add_trace(data = pie2data %>% select(group,count), 
                           labels = ~label2, values = ~count,
                           type = 'pie',
                           
                           name =  pie2data$boro, domain = list(row = 0, column = 1)) 
    fig <- fig %>% add_trace(data = pie3data %>% select(group,count), 
                           labels = ~label3, values = ~count,
                           type = 'pie',
                           
                           name = pie3data$boro, domain = list(row = 0, column = 2)) 
    fig <- fig %>% add_trace(data = pie4data %>% select(group,count), 
                           labels = ~label4, 
                           values = ~count,
                           type = 'pie',
                           
                           name = pie4data$boro, domain = list(row = 0, column = 3)) 
    fig <- fig %>% add_trace(data = pie5data %>% select(group,count), 
                           labels = ~label5, 
                           values = ~count,
                           type = 'pie',
                           name = pie5data$boro, domain = list(row = 0, column = 4)) 
    
    fig <- fig %>% layout(title = "Age Group Pie Chart", showlegend = T,
                          grid=list(rows=1, columns=5),
                          xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = F),
                          yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = F)) %>% 
      add_annotations(x=seq(0.2,0.2+4*0.2,0.2),
                          y=0.3,
                          text = c("Bronx", "Brooklyn", "Manhattan","Queens","Staten Island"),
                          xref = "paper",
                          yref = "paper",
                          xanchor = "center",
                          showarrow = FALSE
                )
    
    fig


```







```{r, eval = FALSE}
demo_by_age = read.csv("./distribution_of_covid-19/data/demoage_data.csv")
boros1 = rep(c("Brooklyn","Bronx","Manhattan","Queens","Staten Island"),258)

boro_age_case_count = demo_by_age %>% 
    filter(str_detect(location_n_event,"CASE_COUNT")) %>% 
    mutate(location = boros1)

boro_age_hosp_count = demo_by_age %>% 
    filter(str_detect(location_n_event,"HOSPITALIZED_COUNT")) %>% 
    mutate(location = boros1)

boro_age_death_count = demo_by_age %>% 
    filter(str_detect(location_n_event,"DEATH_COUNT")) %>% 
    mutate(location = boros1)

boro_age_case_rate = demo_by_age %>% 
    filter(str_detect(location_n_event,"CASE_RATE")) %>% 
    mutate(location = boros1)

boro_age_hosp_rate = demo_by_age %>% 
    filter(str_detect(location_n_event,"HOSPITALIZED_RATE")) %>% 
    mutate(location = boros1)

boro_age_death_rate = demo_by_age %>% 
    filter(str_detect(location_n_event,"DEATH_RATE")) %>% 
    mutate(location = boros1)

```


```{r}


pie1data = byage %>% filter(boro == "BX"& day == max(byage$day) &group != "Boroughwide" & outcome =="CASE_COUNT")

pie1data = pie1data[order(pie1data$group, decreasing = TRUE),]
myLabel = as.vector(pie1data$group)   
myLabel = paste(myLabel, "(", round(pie1data$count / sum(pie1data$count) * 100, 2), "%)", sep = "")   


p = ggplot(pie1data, aes(x = "", y = count, fill = group)) +
  geom_bar(stat = "identity", width = 1) +    
  coord_polar(theta = "y") + 
  labs(x = "", y = "", title = "") + 
  theme(axis.ticks = element_blank()) + 
  theme(legend.title = element_blank(), legend.position = "top") + 
  scale_fill_discrete(breaks = pie1data$group, labels = myLabel) + 
  theme(axis.text.x = element_blank()) + 
  theme(panel.grid=element_blank()) +   
  theme(panel.border=element_blank()) 


```

```{r}

myLabel = as.vector(pie1data$group)   
myLabel = paste(myLabel, "(", round(pie1data$count / sum(pie1data$count) * 100, 2), "%)", sep = "")   


p2 = ggplot(pie1data, aes(x = "", y = count, fill = group)) +
  geom_bar(stat = "identity", width = 1) +    
  coord_polar(theta = "y") + 
  labs(x = "", y = "", title = "") + 
  theme(axis.ticks = element_blank()) + 
  theme(legend.title = element_blank(), legend.position = "top") + 
  scale_fill_discrete(breaks = pie1data$group, labels = myLabel) + 
  theme(axis.text.x = element_blank()) + 
  theme(panel.grid=element_blank()) +   
  theme(panel.border=element_blank()) 


```



```{r}
byage = read_csv("./distribution_of_covid-19/data/demoage_data.csv") %>% 
  mutate(outcome = str_replace_all(outcome, "CASE_COUNT","Case Count"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_COUNT","Hospitalized Count"),
         outcome = str_replace_all(outcome, "DEATH_COUNT","Death Count"),
         outcome = str_replace_all(outcome, "CASE_RATE","Case Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_RATE","Hospitalized Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "DEATH_RATE","Death Rate(per 100,000 people)"),
         boro = str_replace_all(boro, "BK","Brooklyn"),
         boro = str_replace_all(boro, "MN","Manhattan"),
         boro = str_replace_all(boro, "QN","Queens"),
         boro = str_replace_all(boro, "BX","Bronx"),
         boro = str_replace_all(boro, "SI","Staten Island"))
  

byrace = read_csv("./distribution_of_covid-19/data/BYRACE_demoage_data.csv") %>% 
  mutate(outcome = str_replace_all(outcome, "CASE_COUNT","Case Count"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_COUNT","Hospitalized Count"),
         outcome = str_replace_all(outcome, "DEATH_COUNT","Death Count"),
         outcome = str_replace_all(outcome, "CASE_RATE_ADJ","Case Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_RATE_ADJ","Hospitalized Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "DEATH_RATE_ADJ","Death Rate(per 100,000 people)"),
         boro = str_replace_all(boro, "BK","Brooklyn"),
         boro = str_replace_all(boro, "MN","Manhattan"),
         boro = str_replace_all(boro, "QN","Queens"),
         boro = str_replace_all(boro, "BX","Bronx"),
         boro = str_replace_all(boro, "SI","Staten Island"))


bysex = read_csv("./distribution_of_covid-19/data/demoage_data_sex.csv") %>% 
  mutate(outcome = str_replace_all(outcome, "CASE_COUNT","Case Count"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_COUNT","Hospitalized Count"),
         outcome = str_replace_all(outcome, "DEATH_COUNT","Death Count"),
         outcome = str_replace_all(outcome, "CASE_RATE","Case Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "HOSPITALIZED_RATE","Hospitalized Rate(per 100,000 people)"),
         outcome = str_replace_all(outcome, "DEATH_RATE","Death Rate(per 100,000 people)"),
         boro = str_replace_all(boro, "BK","Brooklyn"),
         boro = str_replace_all(boro, "MN","Manhattan"),
         boro = str_replace_all(boro, "QN","Queens"),
         boro = str_replace_all(boro, "BX","Bronx"),
         boro = str_replace_all(boro, "SI","Staten Island"))



```

```{r}

Week <- unique(as.Date(cut(byage$day, "week")) + 6)
    weeklyage <- byage %>% 
      filter(day %in% Week)

    x_min_us = min(weeklyage$day)
    x_max_us = max(weeklyage$day)
    
    break.vec <- c(x_min_us, seq(x_min_us, x_max_us, by = "7 days"))
    
    a = weeklyage %>% 
      filter(group != "Boroughwide" & outcome == "Case Count") %>% 
      ggplot(aes(x = day, y = count ,color = group, group = group)) + 
      geom_line(size = 0.3) + geom_point(size = 0.8) + facet_grid(~boro) + 
      theme_minimal() +  
      scale_x_date(breaks = break.vec, date_labels = "%m-%d") + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
      theme(legend.title = element_blank()) +
      xlab("") + 
      ylab("")
    
    ggplotly(a)
    
```

