---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(viridis)
library(leaflet)

library(maps)
library(tigris)
library(sp)
library(maptools)
library(broom)
library(httr)
library(rgdal)

library(sf)
library(raster)

library(spData)

library(tmap)    # for static and interactive maps

library(shiny)   # for web applications

spdf = rgdal::readOGR("/Users/ziqizhou/Desktop/MSPH_1st_Year/P8105_Data_Science/Git/zipcode_covid-19/data/Geography-resources/MODZCTA_2010_WGS1984.geo.json")
spdf@data

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo = FALSE, warning=FALSE, message=FALSE}
data0614 = read.csv("./data/June/0614/data-by-modzcta0614.csv") %>% 
  drop_na()%>% janitor::clean_names() %>% 
  rename(positive = covid_case_count,
         MODZCTA = modified_zcta) %>% 
  dplyr::select(MODZCTA,positive,neighborhood_name, borough_group)

posi_map = geo_join(spdf,data0614,"MODZCTA","MODZCTA")

pal <- colorNumeric("Greens", domain=posi_map$positive)

# Getting rid of rows with NA values
posi_map <- subset(posi_map, !is.na(positive))

# Setting up the pop up text
popup_sb <- paste0("Positive Cases: ", as.character(posi_map$positive))

# Mapping it with the new tiles CartoDB.Positron
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.75074, zoom = 12) %>% 
  addPolygons(data = posi_map , 
              fillColor = ~pal(posi_map$positive), 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2, 
              popup = ~popup_sb) %>%
  addLegend(pal = pal, 
            values = posi_map$positive, 
            position = "bottomright", 
            title = "Cumulative cases")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE, warning=FALSE, message=FALSE}
data0614_death = read.csv("./data/June/0614/data-by-modzcta0614.csv") %>% 
  drop_na()%>% janitor::clean_names() %>% 
  rename(positive = covid_case_count,
         MODZCTA = modified_zcta) %>% 
  dplyr::select(MODZCTA,covid_death_count)

death_map = geo_join(spdf,data0614_death,"MODZCTA","MODZCTA")
  
pal_dea <- colorNumeric("Reds", domain=death_map$covid_death_count)

# Getting rid of rows with NA values
death_map <- subset(death_map, !is.na(covid_death_count))

# Setting up the pop up text
popup_dea_sb <- paste0("Death Count: ", as.character(death_map$covid_death_count))

# Mapping it with the new tiles CartoDB.Positron
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.75074, zoom = 12) %>% 
  addPolygons(data = death_map , 
              fillColor = ~pal_dea(death_map$covid_death_count), 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2, 
              popup = ~popup_dea_sb) %>%
  addLegend(pal = pal_dea, 
            values = death_map$covid_death_count, 
            position = "bottomright", 
            title = "Death Count")
```

### Chart C

```{r, echo = FALSE, warning=FALSE, message=FALSE}
median_income = read_excel("./data/MedianZIP-3.xlsx") %>% 
  janitor::clean_names() %>% 
  rename(zipcode = zip)

May_newcases = read_csv("./data/May_newcases")

New_York_City_zip = May_newcases %>% 
  distinct(zipcode)

median_income_nyc = left_join(New_York_City_zip, median_income)

median_income_map = geo_join(spdf, median_income_nyc,"MODZCTA", "zipcode")
pal_med = colorNumeric(palette="YlOrRd", domain=median_income_map@data$median, na.color="transparent")

median_income_map = subset(median_income_map, !is.na(median))

popup_medi_sb <- paste0("Median Income: ", as.character(median_income_map$median))

# Mapping it with the new tiles CartoDB.Positron
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.75074, zoom = 12) %>% 
  addPolygons(data = median_income_map , 
              fillColor = ~pal_med(median_income_map$median), 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2, 
              popup = ~popup_medi_sb) %>%
  addLegend(pal = pal_med, 
            values = median_income_map$median, 
            position = "bottomright", 
            title = "Median Annual Income")
```

