---
title: "Demographics"
runtime: shiny
output: 
    flexdashboard::flex_dashboard
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)
library(readxl)
library(viridis)
library(leaflet)
library(plotly)

library(tigris)
library(sp)


library(tmap)    # for static and interactive maps


library(maptools)
library(rgeos)
library(tidyverse)
library(rgdal)
library(ggthemes)

spdf = rgdal::readOGR("Geography-resources/MODZCTA_2010_WGS1984.geo.json")
spdf@data

data_by_modzcta <- read_csv("data/data-by-modzcta.csv") %>% 
  select(1:3) %>% 
  janitor::clean_names() %>% 
  rename(zipcode = modified_zcta)
  

sex_age_raw <- read_csv("data/predictor_data/sex_by_age_zipcode_nyc.csv") %>% select(-1)
sex_age <- left_join(sex_age_raw, data_by_modzcta) %>% 
  select(zipcode, neighborhood_name, borough_group, everything())

income_raw <- read_csv("data/predictor_data/median_income_nyc.csv") %>% select(-1)
income <- left_join(income_raw, data_by_modzcta) %>% 
  select(zipcode, neighborhood_name, borough_group, everything())

household_raw <- read_csv("data/predictor_data/household_zipcode_nyc.csv") %>% select(-1)
household <- left_join(household_raw, data_by_modzcta) %>% 
  select(zipcode, neighborhood_name, borough_group, everything())

race_raw <- read_csv("data/predictor_data/race_by_zipcode_nyc.csv") %>% select(-1)
race <- left_join(race_raw, data_by_modzcta) %>% 
  select(zipcode, neighborhood_name, borough_group, everything())

race_new = 
  rbind(race,c(99999, rep(0,10)))
```

Race 
=======================================================================    
   
Column {data-width=600 }
-----------------------------------------------------------------------
### Chart 1

```{r using plot()}
mergedata <- merge(race_new, spdf@data, by.y = "MODZCTA", by.x = "zipcode", sort=FALSE)
num.dots <- select(mergedata, white_alone:two_or_more_races) / 100

sp.dfs <- lapply(names(num.dots), function(x) {
  dotsInPolys(spdf, as.integer(num.dots[,x]), f="random")
})

pal <- c("#8DD3C7", "#FFFFB3", "#BEBADA", "#FB8072", "#80B1D3", "#FDB462", "#B3DE69")



par(mar = c(0,0,0,0))
plot(spdf, lwd = 0.01, border = "black")
for (i in 1:length(sp.dfs)) {
  plot(sp.dfs[[i]], add = T, pch = 16, cex = 0.1, col = pal[i])
}
```


```{r using ggplot}
spdf@data$id <- row.names(spdf@data)
spdf.points <- fortify(spdf, region = "id")
spdf.df <- merge(spdf.points, spdf@data, by = "id") %>% 
  filter(MODZCTA != 99999)

ggplot(spdf.df, aes(long, lat, group = group)) +
  geom_path() +
  coord_map()

dfs <- lapply(sp.dfs, function(x) {
  data.frame(coordinates(x)[,1:2])
})

race_name <- str_replace_all(names(race_new[,5:11]), "_", " ") 

for (i in 1:length(race_name)) {
  dfs[[i]]$Race <- race_name[i]
}

dots.final <- bind_rows(dfs)
dots.final$Race <- factor(dots.final$Race, levels = race_name)



ggplot(spdf.df) +
  geom_point(data = dots.final, aes(x, y, colour = Race), size = 0.01, alpha = 0.5) +
  geom_path(aes(long, lat, group = group), colour = "black", size = 0.05) +
  scale_colour_manual(values = pal) +
  theme_map() +
  coord_map()


```


```{r using leaflet}
posi_map_race = geo_join(spdf,race,"MODZCTA","zipcode")
      
pal <- colorFactor("Spectral", unique(dots.final$Race))

posi_map_race <- subset(posi_map_race, !is.na(total))


      # Setting up the pop up text
      popup_sb <- paste0("<b> ZCTA: </b>", posi_map_race$zipcode, 
                         "<br>", 
                         "<b> NBH: </b>", posi_map_race$neighborhood_name,
                         "<br>", 
                         "<b> Borough: </b>", posi_map_race$borough_group,
                         "<br>", 
                         "<b> Total: </b>", posi_map_race$total,
                         "<br>", 
                         "<b> White alone: </b>", posi_map_race$white_alone,
                         "<br>", 
                         "<b> Black or African American alone: </b>",posi_map_race$black_or_african_american_alone,
                         "<br>", 
                         "<b> American indian and Alaska native alone: </b>", posi_map_race$american_indian_and_alaska_native_alone,
                         "<br>", 
                         "<b> Asian alone: </b>", posi_map_race$asian_alone,
                         "<br>", 
                         "<b> Native Hawaiian and other Pacific Islander alone: </b>", posi_map_race$native_hawaiian_and_other_pacific_islander_alone,
                         "<br>", 
                         "<b> Some other race alone: </b>", posi_map_race$some_other_race_alone,
                         "<br>", 
                         "<b> Two or more races: </b>", posi_map_race$two_or_more_races)
      
      
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.71181, zoom = 11) %>% 
        addPolygons(data = posi_map_race, 
                    fillColor = "white", 
                    fillOpacity = 0.00001, 
                    weight = 0.2, 
                    smoothFactor = 0.2,
                    popup = ~popup_sb) %>%
        addCircleMarkers(data = dots.final, lng = dots.final$x, lat = dots.final$y,
                         color = ~pal(Race),
                         radius = 1,
                         stroke = FALSE, fillOpacity = 0.5) %>% 
        addLegend(pal = pal, 
                  values = unique(dots.final$Race), 
                  position = "bottomright", 
                  title = "Total population")

```

Column {data-width=400}
----------------------------------------------------------------------- 
### Chart 2

```{r}
race_gp = race %>% 
  pivot_longer(white_alone:two_or_more_races, names_to = "race", values_to = "population") %>% 
  group_by(borough_group, race) %>% 
  summarise(pop = sum(population))
  


plot_ly(x = forcats::fct_reorder(race_gp$borough_group, race_gp$pop),
        y = race_gp$pop,
        type = "bar",
        color = race_gp$race,
        colors = "Spectral",
        opacity=0.8) %>% 
  layout(boxmode = "group",
         legend=list(title=list(text='<b> Race </b>'), orientation = 'h', xanchor = "center", x = 0.5)
         )
```   


Income {data-orientation=columns}
=======================================================================   
   
Column {data-width=600 .tabset}
-----------------------------------------------------------------------
### Chart 1

```{r}
posi_map_income = geo_join(spdf,income,"MODZCTA","zipcode")

pal <- colorNumeric("Greens", domain=posi_map_income$median)

# Getting rid of rows with NA values
posi_map_income <- subset(posi_map_income, !is.na(median))

# Setting up the pop up text
popup_sb <- paste0("ZCTA: ", posi_map_income$zipcode, 
                   "<br>", 
                   "NBH: ", posi_map_income$neighborhood_name,
                   "<br>", 
                   "Borough: ", posi_map_income$borough_group,
                   "<br>", 
                   "Median Income: $", as.character(round(posi_map_income$median),0))


leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.75074, zoom = 12) %>% 
  addPolygons(data = posi_map_income , 
              fillColor = ~pal(posi_map_income$median), 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2,
              popup = ~popup_sb) %>%
  addLegend(pal = pal, 
            values = posi_map_income$median, 
            position = "bottomright", 
            title = "Median Income")
```

### Chart 2

```{r}
posi_map_income = geo_join(spdf,income,"MODZCTA","zipcode")

pal <- colorNumeric("Greens", domain=posi_map_income$mean)

# Getting rid of rows with NA values
posi_map_income <- subset(posi_map_income, !is.na(mean))

# Setting up the pop up text
popup_sb <- paste0("ZCTA: ", posi_map_income$zipcode, 
                   "<br>", 
                   "NBH: ", posi_map_income$neighborhood_name,
                   "<br>", 
                   "Borough: ", posi_map_income$borough_group,
                   "<br>", 
                   "Mean Income: $", as.character(round(posi_map_income$mean),0))


leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(lng = -73.99653, lat = 40.75074, zoom = 12) %>% 
  addPolygons(data = posi_map_income , 
              fillColor = ~pal(posi_map_income$mean), 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2,
              popup = ~popup_sb) %>%
  addLegend(pal = pal, 
            values = posi_map_income$mean, 
            position = "bottomright", 
            title = "Mean Income")
```   
    

Column {data-width=400}
-----------------------------------------------------------------------   
### Chart 3

```{r}
income_gp = income %>% 
  pivot_longer(mean:median, names_to = "stat", values_to = "value")
  

#  group_by(borough_group) %>% 
#  summarise(mean = round(mean(mean, na.rm = TRUE),0),
#            median = round(median(median, na.rm = TRUE),0)) %>% 

plot_ly(x = forcats::fct_reorder(income_gp$borough_group, income_gp$value),
        y = income_gp$value,
        type = "box",
        color = income_gp$stat,
        colors = "Set1") %>% 
  layout(boxmode = "group",
         legend=list(title=list(text='<b> Statistics </b>')))
```   
    
### Chart 4

```{r}

```

Household {data-orientation=columns}
=======================================================================   
   
Column {data-width=600}
-----------------------------------------------------------------------
### Chart 1

```{r}
```

Column {data-width=400}
-----------------------------------------------------------------------   
### Chart 2

```{r}
household_gp = household %>% 
  pivot_longer("1":"7_or_more", names_to = "size", values_to = "number")
  
plot_ly(x = forcats::fct_reorder(household_gp$borough_group, household_gp$number),
        y = household_gp$number,
        type = "box",
        colors = "Spectral",
        color = household_gp$size) %>% 
  layout(boxmode = "group",
         legend=list(title=list(text='<b> Family Size </b>')))

```   
    
### Chart 3

```{r}

    output$household_boro <- renderPlotly({
      
      household_gp = household %>% 
        pivot_longer("1":"7_or_more", names_to = "size", values_to = "number") %>% 
        group_by(borough_group, size) %>% 
        summarise(num = sum(number))
      
      plot_ly(x = forcats::fct_reorder(household_gp$borough_group, household_gp$num),
              y = household_gp$num,
              type = "bar",
              color = household_gp$size,
              colors = "Spectral",
              opacity=0.8) %>% 
        layout(boxmode = "group",
               legend=list(title=list(text='<b> Family Size </b>')))
    
      
    })
    
    
    output$household_nbh <- renderPlotly({
      household_nbh = household %>% 
        filter(neighborhood_name == input$nbhid) %>%
        pivot_longer("1":"7_or_more", names_to = "size", values_to = "number") %>%
        group_by(neighborhood_name, size) %>% 
        summarise(num = sum(number)) %>% 
        drop_na()
      
      plot_ly(labels = household_nbh$size,
              values = household_nbh$num,
              type = "pie",
              colors = "Spectral",
              opacity=0.8) %>% 
        layout(legend=list(title=list(text='<b> Family Size </b>'), orientation = 'h', xanchor = "center", x = 0.5))
      
    })
```