---
title: "MapGif"
author: "Ziqi Zhou"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gganimate)
library(tidyverse)

library(magrittr)
library(leaflet)
library(maps)
library(tigris)
library(sf)
library(RColorBrewer)
#library(plotly)
#library(rnaturalearth)
library(lubridate)
```

```{r}
#read the data
Aprildata_with_nebhod = read_csv("./data/Aprildata_with_nebhod.csv") %>% 
  rename(zipcode = MODZCTA) %>% 
  mutate(month = 4) %>% 
  select(zipcode,positive,month, date) 

#Aprildata_with_nebhod = read_csv("./data/Aprildata_with_nebhod.csv") %>% 
  #rename(zipcode = MODZCTA) %>% 
  #mutate(month = 4) %>% 
  #select(MODZCTA,positive,month, date) 

finalMaydata <- read_csv("data/May_data.csv") %>% 
mutate(month = 5,
       zipcode = modified_zcta) %>% 
  select(zipcode,positive,month, date) 

final_Junedata <- read_csv("data/final_Junedata.csv")%>% 
 mutate(date = day(day),
         month = month(day)) %>% 
  select(zipcode,positive,month, date) 

  
final_Julydata = read_csv("data/final_Julydata.csv") %>% 
  mutate(date = day(day),
         month = month(day)) %>% 
  select(zipcode,positive,month, date)


#data = rbind(Aprildata_with_nebhod, finalMaydata)
data <- rbind(finalMaydata,final_Junedata)
data <- rbind(data,final_Julydata)
```


```{r}
Aug_data = read_csv("nyc-neighborhoods-covid/data/Aug19data.csv") %>% 
  rename("covid_case_count" = positive,
         modified_zcta = zipcode,
         date = day) 
```



```{r}
newdeath = 0

for (i in 1:177) {
  newdeath[i] = 0 

}

for (i in 178:3186) {
  newdeath[i] = Aug_data[i,7] - Aug_data[i-177,7]
}

Aug_data = Aug_data %>% 
  mutate(newdeath = newdeath,
         newdeath = as.integer(newdeath)) %>% 
  filter(date != "2020-08-01") %>% 
  rename(
         new_death = newdeath) %>% 
  mutate(new_case = as.numeric(new_case),
         new_death = as.numeric(new_death),
         incidence_rate = round(new_case*100000/pop_denominator, digits = 1) ) 

aug01_1 = aug01_1 %>% 
  rename(new_case = newcases)
Aug_data = rbind(aug01_1,Aug_data)


```


```{r}
aug01 = Aug_data %>% 
  filter(date == min(date))
July31 = July31 %>% 
  rename("covid_case_count" = positive,
         modified_zcta = zipcode,
         date = day)
data01 = rbind(aug01, July31) 

new_death = 0

for (i in 1:177) {
  #new_case[i] = data01[i,4] - data01[i+177,4]
  #new_case
  
  new_death[i] = data01[i,7] - data01[i+177,7]
  new_death
}

for (i in 178:354) {
  
  #new_case[i] = NA
  
  new_death[i] = NA
}


  
```

#read the new aug data
today-yesterday = today new
```{r}
aug19 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta819.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-19")) 

aug20 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta820.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-20"))
aug21 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta821.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-21")) 

aug22 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta822.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-22")) 
aug23 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta823.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-23")) 
aug24 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta824.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-24")) 
aug25 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta825.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-25")) 
aug26 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta826.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-26")) 
aug27 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta827.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-27")) 
aug28 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta828.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-28")) 
aug29 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta829.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-29")) 
aug30 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta830.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-30")) 
aug31 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta831.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-08-31")) 

sep01 = read_csv("nyc-neighborhoods-covid/data/data_for_table/data-by-modzcta91.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date("2020-09-01")) 


NewAugdata = rbind(aug19_1, aug20_1)
NewAugdata = rbind(NewAugdata, aug21_1)
NewAugdata = rbind(NewAugdata, aug22_1)
NewAugdata = rbind(NewAugdata, aug23_1)
NewAugdata = rbind(NewAugdata, aug24_1)
NewAugdata = rbind(NewAugdata, aug25_1)
NewAugdata = rbind(NewAugdata, aug26_1)
NewAugdata = rbind(NewAugdata, aug27_1)
NewAugdata = rbind(NewAugdata, aug28_1)
NewAugdata = rbind(NewAugdata, aug29_1)
NewAugdata = rbind(NewAugdata, aug30_1)
NewAugdata = rbind(NewAugdata, aug31_1)

#write_csv(NewAugdata, "./data/NewAugdata")

Augdata = rbind(Aug_data,NewAugdata)
#write_csv(Augdata, "./data/Augdata_final.csv")
```


data we have
from May 18 to Aug 31

```{r}
May18to30 = read_csv("data/May_data.csv") %>% 
  filter(date >= 19)
  
Juneall = read_csv("data/final_Junedata.csv") %>% 
  select(-X1)



Julyall = read_csv("data/final_Julydata.csv") %>% 

#Augdata is from august 1 to 31
Augdata
```

```{r}
data <- rbind(data,final_Aug_data)
data = data %>% 
  rename(MODZCTA = zipcode)
#data <- rbind(data,Augdata)

### original d not available
spdf2 = read_sf("Geography-resources/MODZCTA_2010_WGS1984.geo.json")
```

```{r}
Aprildata_with_nebhod_break = Aprildata_with_nebhod
Aprildata_with_nebhod_break$positive = cut(Aprildata_with_nebhod$positive, 
                                     breaks = c(0,50,100,200,500,1000,
                                                2000,3000,4000,10000),
                                     labels = c('0-50','50-100','100-200','200-500',
                                                '500-1000','1000-2000',
                                                '2000-3000','3000-4000','4000+'),
                                    order = TRUE,include.lowest = TRUE, right = TRUE)
```



```{r}
data_break = data
data_break$positive = cut(data$positive, 
                                     breaks = c(0,50,100,200,500,1000,
                                                2000,3000,4000,10000),
                                     labels = c('0-50','50-100','100-200','200-500',
                                                '500-1000','1000-2000',
                                                '2000-3000','3000-4000','4000+'),
                                   order = TRUE,include.lowest = TRUE, right = TRUE)



```

```{r}
i = 3
#j= 4
 p =  Aprildata_with_nebhod_break %>% 
    dplyr::filter(date == i) %>% 
   mutate(MODZCTA = as.character(MODZCTA)) %>% 
   #dplyr::select(-zcta_cum_perc_pos) %>% 
    left_join(spdf2, ., by = c('MODZCTA' = 'MODZCTA')) 
 p = subset(p, !is.na(positive))
    
aprplot = ggplot(p) + 
    geom_sf(aes(fill = positive)) + 
    coord_sf()+
    scale_fill_brewer(palette = "OrRd",direction = 1) + 
    labs(title = paste0("COVID-19 in NYC at ZCTAs level on : ", j ,"/" ,i,"/2020"))

    #ggsave(filename = paste0(i,"_2020FromApritoJuly.png"),   width = 10, height = 10, units = "cm")
```

## plotly animation

```{r}
df.p = Aprildata_with_nebhod_break %>% 
    mutate(MODZCTA = as.character(MODZCTA)) %>% 
    #dplyr::select(-zcta_cum_perc_pos) %>% 
    left_join(spdf2, ., by = c('MODZCTA' = 'MODZCTA')) 
df.p = subset(df.p, !is.na(positive))

```



```{r}

data_break_may =  data_break %>% 
    dplyr::filter(month == 7) 

for (i in 1:9) {
     p =  data_break_may %>% 
    dplyr::filter(date == i) %>% 
   mutate(MODZCTA = as.character(MODZCTA)) %>% 
   #dplyr::select(-zcta_cum_perc_pos) %>% 
    left_join(spdf2, ., by = c('MODZCTA' = 'MODZCTA'))
     
     p = subset(p, !is.na(positive))
    plot = 
      a = ggplot(p) + 
      geom_sf(aes(fill = positive)) + 
    coord_sf()+
    scale_fill_brewer(palette = "OrRd",direction = 1) + 
    labs(title = paste0("COVID-19 in NYC at ZCTAs level on : ", 7 ,"/0" ,i,"/2020"))

    ggsave(filename = paste0("2020-FromApritoJuly","7-0",i,".png"), plot = a, path = "./allpics/",width = 20, height = 20, units = "cm")
  
  
}


for (i in 10:31) {
     p =  data_break_may %>% 
    dplyr::filter(date == i) %>% 
   mutate(MODZCTA = as.character(MODZCTA)) %>% 
   #dplyr::select(-zcta_cum_perc_pos) %>% 
    left_join(spdf2, ., by = c('MODZCTA' = 'MODZCTA'))
     
     p = subset(p, !is.na(positive))
    plot = 
      a = ggplot(p) + 
      geom_sf(aes(fill = positive)) + 
    coord_sf()+
    scale_fill_brewer(palette = "OrRd",direction = 1) + 
    labs(title = paste0("COVID-19 in NYC at ZCTAs level on : ", 7 ,"/" ,i,"/2020"))

    ggsave(filename = paste0("2020-FromApritoJuly","7-",i,".png"), plot = a, path = "./allpics/",width = 20, height = 20, units = "cm")
  
  
}


#system("ffmpeg -i warming.mp4 -vf 'setpts=2*PTS' warming_slow.mp4")
```

```{r}
library(magick)
list.files(path='./allpics/', pattern = '*.png', full.names = TRUE) %>% 
        image_read() %>% # reads each path file
        image_join() %>% # joins image
        image_animate(fps=4) %>% # animates, can opt for number of loops
        image_write("JulyMap.gif")

```

```{r}

#animate_p = image_animate(image=image_read(path=paste0("/Users/ziqizhou/Desktop/MSPH_1st_Year/P8105_Data_Science/Git/NYC_covid-19.github.io/allpics/2020-FromApritoJuly7-9.png")))
animate_p = image_animate(image=image_read(list.files(path='./allpics/July', pattern = '*.png', full.names = TRUE)))


av::av_encode_video(list.files(path='./allpics/', pattern = '*.png', full.names = TRUE), framerate = 4,
                    output = 'test.mp4')

#anim_save(filename = "aprmap.gif",animation = animate_p,path="/Users/ziqizhou/Desktop/MSPH_1st_Year/P8105_Data_Science/Git/NYC_covid-19.github.io/data/pics")

#print(animate_p) # too fast
```

