---
title: "Projection"
author: "Ziqi Zhou"
date: "8/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(readxl)
```

# City Level

```{r}
proje = read_xlsx("./data/WeeklyProjections20200828.xlsx",sheet = 4) %>% 
  janitor::clean_names()
```

```{r}
#seasonality assumed
#city
#new infections
season_city_newinf = proje %>% 
  filter(seasonality == "Seasonality assumed" & intervention == "As Is" & location == "city") %>% 
  separate(col = new_infections, into = c("new_infe_value","new_infe_lower","new_infe_upper")) %>%
  mutate(new_infe_value = as.integer(new_infe_value),
         new_infe_lower = as.integer(new_infe_lower),
         new_infe_upper = as.integer(new_infe_upper))
```

```{r}
p <- ggplot(season_city_newinf) + 
  geom_path(aes(y=new_infe_value, x=date, colour = "Projected Median Number",group = 1))+
  geom_ribbon(aes(ymin=new_infe_lower, 
                  ymax=new_infe_upper, 
                  x=date, fill = "IQR"), alpha = 0.2,group = 1) + 
  
    scale_colour_manual("",values="red") + 
    scale_fill_manual("",values="grey12") + 
    theme_bw() +
      theme(panel.border = element_blank()) +
      theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.line = element_line(colour = "black")) +
      theme(strip.background = element_blank()) + 
      theme(axis.text.x = element_text(angle = 65, hjust = 1)) + 
      theme(panel.spacing.y=unit(1, "lines")) + 
  xlab("")+
  ylab("New Infections")
p
```


#draw a plot
first half is the trueth and the second half is the next eight weeks projections.

```{r}

#data clean of first half of
borocase_new <- read_csv("data/boro_newcase_trend.csv") %>% select(-1)
borocase_cum <- read_csv("data/boro_cumcase_trend.csv") %>% select(-1)
week <- as.Date(cut(borocase_cum$date_of_interest, "week")) + 6

weeklydf_new <- borocase_new %>% 
  mutate(week = week) %>% 
  group_by(boro,week) %>% 
  summarise(case_count = sum(case_count),
            hospitalization_count = sum(hospitalized_count),
            death_count = sum(death_count)) %>% 
  pivot_longer(case_count:death_count,
               names_to = "type",
               values_to = "count") %>% 
  mutate(type = str_to_title(str_replace_all(type, "_", " ")),
         newtype = str_replace_all(paste(type, "Rate"),"Count ",""),
         pop_num = ifelse(boro == "Bronx", 1434693, 
                          ifelse(boro == "Brooklyn",2582830, 
                                 ifelse(boro == "Manhattan",1611943, 
                                        ifelse(boro == "Staten Island", 476179,
                                               ifelse(boro == "Queens", 2288710, 2288710))))),
         rate = round(count/pop_num*1000000,1)) %>% 
  rename(Borough = boro,
         Date = week,
         Count = count,
         Rate = rate) %>% 
  mutate(type = str_replace_all(type,"Case Count", "Total Cases"),
         type = str_replace_all(type,"Death Count", "Total Deaths"),
         type = str_replace_all(type,"Hospitalization Count", "Total Hospitalizations"),
         newtype = str_replace_all(newtype,"Case Rate","Case Rate (per 100,000 people)"),
         newtype = str_replace_all(newtype,"Death Rate","Death Rate (per 100,000 people)"),
         newtype = str_replace_all(newtype,"Hospitalization Rate","Hospitalization Rate (per 100,000 people)"))%>% 
  mutate(type = factor(type, levels = c("Total Cases","Total Deaths","Total Hospitalizations")),
         newtype = factor(newtype, levels = c("Case Rate (per 100,000 people)","Death Rate (per 100,000 people)","Hospitalization Rate (per 100,000 people)"))) %>% 
  arrange(type) %>% 
  arrange(newtype)
```
```{r}
weeklydf_new %>% 
    ggplot(aes(x = Date, y = Count)) + 
    geom_line(aes(color = Borough)) +
    geom_point(aes(color = Borough)) +
    facet_wrap(.~type, scales = "free") +
    theme_minimal() +
    #theme(legend.position = "none")+
    #theme(panel.spacing.y=unit(2, "lines")) + 
    xlab("") + 
    ylab("")
```


###########

#what we can combine together

Is that really reasonable?

New cases
New total hospitalizations
New deaths

1. New cases

```{r}
#new cases
season_city_newcases = proje %>% 
  filter(seasonality == "Seasonality assumed" & intervention == "As Is" & location == "city") %>% 
  separate(col = new_cases, into = c("new_cases_value","new_cases_lower","new_cases_upper")) %>%
  mutate(new_cases_value = as.numeric(new_cases_value),
         new_cases_lower = as.numeric(new_cases_lower),
         new_cases_upper = as.numeric(new_cases_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")
         ) %>% 
  select(date, new_cases_value,new_cases_lower,new_cases_upper,week)
#date = as.Date(date,format = "%m/%d/%Y")
```

```{r}
#Daily New Cases, Death, Hospitalization
case_hosp_death <- read.csv(curl("https://raw.github.com/nychealth/coronavirus-data/master/case-hosp-death.csv")) %>% janitor::clean_names()
Week <- unique(as.Date(cut(as.Date(case_hosp_death$date_of_interest,format = "%m/%d/%y"), "week")) + 6)
Week[28] = as.Date("2020-02-29")
Week = as.data.frame(Week) %>%  arrange(Week)

case = case_hosp_death %>% 
mutate(date_of_interest = as.Date(date_of_interest,format = "%m/%d/%y"),
  wday = wday(date_of_interest),
                 wday.name = wday(date_of_interest, label = TRUE, abbr = TRUE),
  week = format(date_of_interest, format="%Y-%U")) %>% 
  group_by(week) %>% 
  summarize(weekly_newcases = sum(case_count))

df = cbind(case, Week) %>% 
  rename(date = Week)

a = ggplot() + 
    geom_line(data = df,aes(x = date, y = weekly_newcases,group = 1)) +
    geom_point(data = df, aes(x = date, y = weekly_newcases)) +
    theme_minimal() +
    #theme(legend.position = "none")+
    #theme(panel.spacing.y=unit(2, "lines")) + 
  #ggplot(season_city_newcases) + 
  geom_path(data = season_city_newcases,aes(y=new_cases_value, x=date, colour = "Projected Median Number",group = 1))+
  geom_ribbon(data = season_city_newcases, aes(ymin=new_cases_lower, 
                  ymax=new_cases_upper, 
                  x=date, fill = "IQR"), alpha = 0.2,group = 1) + 
    scale_colour_manual("",values="red") + 
    scale_fill_manual("",values="grey12") + 
    theme_bw() +
      theme(panel.border = element_blank()) +
      theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.line = element_line(colour = "black")) +
      theme(strip.background = element_blank()) + 
      theme(axis.text.x = element_text(angle = 65, hjust = 1)) + 
      theme(panel.spacing.y=unit(1, "lines")) + 
  theme(legend.position = "none") +
    theme(legend.text  = element_blank()) +
    xlab("") + 
    ylab("") + 
  ggtitle("New Cases Under As Is Control Scenarios")
ggplotly(a)
```



2.New total hospitalizations

```{r}
season_city_newhosp = proje %>% 
  filter(seasonality == "Seasonality assumed" & intervention == "As Is" & location == "city") %>% 
  separate(col = new_total_hospitalizations, into = c("new_hosp_value","new_hosp_lower","new_hosp_upper")) %>%
  mutate(new_hosp_value = as.integer(new_hosp_value),
         new_hosp_lower = as.integer(new_hosp_lower),
         new_hosp_upper = as.integer(new_hosp_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")) %>% 
  select(date, new_hosp_value,new_hosp_lower,new_hosp_upper,week)
```

```{r}
hosp =case_hosp_death %>% 
mutate(date_of_interest = as.Date(date_of_interest,format = "%m/%d/%y"),
  wday = wday(date_of_interest),
                 wday.name = wday(date_of_interest, label = TRUE, abbr = TRUE),
  week = format(date_of_interest, format="%Y-%U")) %>% 
  group_by(week) %>% 
  summarize(weekly_newcases = sum(hospitalized_count))
df_hosp = cbind(hosp, Week) %>% 
  rename(date = Week)

b = ggplot() + 
    geom_line(data = df_hosp ,aes(x = date, y = weekly_newcases,group = 1)) +
    geom_point(data = df_hosp , aes(x = date, y = weekly_newcases)) +
    theme_minimal() +
    #theme(legend.position = "none")+
    #theme(panel.spacing.y=unit(2, "lines")) + 
  #ggplot(season_city_newcases) + 
  geom_path(data = season_city_newhosp,aes(y=new_hosp_value, x=date, colour = "Projected Median Number",group = 1))+
  geom_ribbon(data = season_city_newhosp, aes(ymin=new_hosp_lower, 
                  ymax=new_hosp_upper, 
                  x=date, fill = "IQR"), alpha = 0.2,group = 1) + 
    scale_colour_manual("",values="red") + 
    scale_fill_manual("",values="grey12") + 
    theme_bw() +
      theme(panel.border = element_blank()) +
      theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.line = element_line(colour = "black")) +
      theme(strip.background = element_blank()) + 
      theme(axis.text.x = element_text(angle = 65, hjust = 1)) + 
      theme(panel.spacing.y=unit(1, "lines")) + 
   theme(legend.position = "none")+
    xlab("") + 
    ylab("") + 
  ggtitle("New Total Hospitalizations Under As Is Control Scenarios")

ggplotly(b)
```

3.New deaths

```{r}
season_city_newdeaths = proje %>% 
  filter(seasonality == "Seasonality assumed" & intervention == "As Is" & location == "city") %>% 
  separate(col = new_deaths, into = c("new_deaths_value","new_deaths_lower","new_deaths_upper")) %>%
  mutate(new_deaths_value = as.integer(new_deaths_value),
         new_deaths_lower = as.integer(new_deaths_lower),
         new_deaths_upper = as.integer(new_deaths_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")) %>% 
  select(date, new_deaths_value,new_deaths_lower,new_deaths_upper,week)
```

```{r}
death =case_hosp_death %>% 
mutate(date_of_interest = as.Date(date_of_interest,format = "%m/%d/%y"),
  wday = wday(date_of_interest),
                 wday.name = wday(date_of_interest, label = TRUE, abbr = TRUE),
  week = format(date_of_interest, format="%Y-%U")) %>% 
  group_by(week) %>% 
  summarize(weekly_newdeaths = sum(death_count))

df_death = cbind(death, Week) %>% 
  rename(date = Week)

c = ggplot() + 
    geom_line(data = df_death ,aes(x = date, y = weekly_newdeaths,group = 1)) +
    geom_point(data = df_death , aes(x = date, y = weekly_newdeaths)) +
    theme_minimal() +
    #theme(legend.position = "none")+
    #theme(panel.spacing.y=unit(2, "lines")) + 
  #ggplot(season_city_newcases) + 
  geom_path(data = season_city_newdeaths,aes(y=new_deaths_value, x=date, colour = "Projected Median Number",group = 1))+
  geom_ribbon(data = season_city_newdeaths, aes(ymin=new_deaths_lower, 
                  ymax=new_deaths_upper, 
                  x=date, fill = "IQR"), alpha = 0.2,group = 1) + 
    scale_colour_manual("",values="red") + 
    scale_fill_manual("",values="grey12") + 
    theme_bw() +
      theme(panel.border = element_blank()) +
      theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.line = element_line(colour = "black")) +
      theme(strip.background = element_blank()) + 
      theme(axis.text.x = element_text(angle = 65, hjust = 1)) + 
      theme(panel.spacing.y=unit(1, "lines")) + 
   #theme(legend.text  = element_blank()) +
  theme(legend.position = "none")+
    xlab("") + 
    ylab("") + + 
  ggtitle("New Deaths Under As Is Control Scenarios")

ggplotly(c)
```


###


```{r}
train_data =read_xlsx("./data/WeeklyProjections20200901.xlsx",sheet = 3) %>% 
  janitor::clean_names()
project_data = read_xlsx("./data/WeeklyProjections20200901.xlsx",sheet = 4) %>% 
  janitor::clean_names()
```
#choose the season assumption
#choose the location
#choose the intervention

```{r}
#we could choose the location
season_city_newcases = project_data %>% 
  filter(seasonality == "Seasonality assumed" & intervention == "As Is" & location == "city") %>% 
  separate(col = new_cases, into = c("new_cases_value","new_cases_lower","new_cases_upper")) %>%
  mutate(new_cases_value = as.numeric(new_cases_value),
         new_cases_lower = as.numeric(new_cases_lower),
         new_cases_upper = as.numeric(new_cases_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")
         ) %>% 
  separate(col = new_deaths, into = c("new_deaths_value","new_deaths_lower","new_deaths_upper")) %>%
  mutate(new_deaths_value = as.integer(new_deaths_value),
         new_deaths_lower = as.integer(new_deaths_lower),
         new_deaths_upper = as.integer(new_deaths_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")) %>% 
 separate(col = new_total_hospitalizations, into = c("new_hosp_value","new_hosp_lower","new_hosp_upper")) %>%
  mutate(new_hosp_value = as.integer(new_hosp_value),
         new_hosp_lower = as.integer(new_hosp_lower),
         new_hosp_upper = as.integer(new_hosp_upper),
         date = as.Date(date,format = "%m/%d/%y"),
         week = format(date, format="%Y-%U")) 

train_data_sel = train_data %>% 
  filter(seasonality == "Seasonality assumed"  & location == "city") %>% 
  separate(col = new_cases, into = c("new_cases_value","new_cases_lower","new_cases_upper")) %>%
  mutate(new_cases_value = as.numeric(new_cases_value),
         new_cases_lower = as.numeric(new_cases_lower),
         new_cases_upper = as.numeric(new_cases_upper))%>% 
  separate(col = new_deaths, into = c("new_deaths_value","new_deaths_lower","new_deaths_upper")) %>%
  mutate(new_deaths_value = as.integer(new_deaths_value),
         new_deaths_lower = as.integer(new_deaths_lower),
         new_deaths_upper = as.integer(new_deaths_upper)
         ) %>% 
 separate(col = new_total_hospitalizations, into = c("new_hosp_value","new_hosp_lower","new_hosp_upper")) %>%
  mutate(new_hosp_value = as.integer(new_hosp_value),
         new_hosp_lower = as.integer(new_hosp_lower),
         new_hosp_upper = as.integer(new_hosp_upper),
         date = as.Date(date,format = "%m/%d/%y")
         ) 
```

```{r}
#plot
b = ggplot() + 
    geom_line(data = train_data_sel ,aes(x = date, y = new_hosp_value,group = 1)) +
    geom_point(data = train_data_sel , aes(x = date, y = new_hosp_value)) +
    theme_minimal() +
    #theme(legend.position = "none")+
    #theme(panel.spacing.y=unit(2, "lines")) + 
  #ggplot(season_city_newcases) + 
  geom_path(data = season_city_newcases,aes(y=new_hosp_value, x=date, colour = "Projected Median Number",group = 1))+
  geom_ribbon(data = season_city_newcases, aes(ymin=new_hosp_lower, 
                  ymax=new_hosp_upper, 
                  x=date, fill = "IQR"), alpha = 0.2,group = 1) + 
    scale_colour_manual("",values="red") + 
    scale_fill_manual("",values="grey12") + 
    theme_bw() +
      theme(panel.border = element_blank()) +
      theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) +
      theme(axis.line = element_line(colour = "black")) +
      theme(strip.background = element_blank()) + 
      theme(axis.text.x = element_text(angle = 65, hjust = 1)) + 
      theme(panel.spacing.y=unit(1, "lines")) + 
   theme(legend.position = "none")+
    xlab("") + 
    ylab("") + 
  ggtitle("New Total Hospitalizations Under As Is Control Scenarios")

ggplotly(b)
```

